modLoader="javafml"
loaderVersion="[36,)"

issueTrackerURL="https://github.com/c0d3break3r/TheHallow/issues"
license="Pugz, All Rights Reserved"

[[mods]]
    modId="custom"
    version="0.0.1"
    displayName="Custom Mod"
    authors="Pugz"
    credits=""
    description='''Create custom blocks!'''

[[dependencies.custom]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.custom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"